name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.2
  - pip=20.3.3
  - scikit-learn=1.2.0
  - matplotlib=3.6.0
  - plotly=5.11.0
  - pillow=9.4.0
  - mlflow=1.29.0
  - pip:
      - wandb==0.13.7
      - omegaconf==2.3.0